version: '3.3'

networks:
  webapp:

services:
  db:
    image: mysql:5.6
    container_name: "${PROJECT_NAME}_mysql5_6"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - webapp
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"


  dbms:
    image: phpmyadmin
    container_name: "${PROJECT_NAME}_phpmyadmin"
    restart: unless-stopped
    networks:
      - webapp
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT}
      - PMA_ARBITRARY=1


  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: "${PROJECT_NAME}_php"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
    networks:
      - webapp
    ports:
      - "${PHP_PORT}:9000"


  server:
    image: nginx:stable-alpine
    container_name: "${PROJECT_NAME}_nginx"
    restart: unless-stopped
    networks:
      - webapp
    depends_on:
      - db
      - php
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
      - ${NGINX_VOLUME}/default.conf:/etc/nginx/conf.d/default.conf