version: '3.3'

services:
    dbms:
      image: phpmyadmin
      container_name: example_phpmyadmin
      restart: always
      depends_on:
            - db
      ports:
            - 8080:80
      environment:
            - UPLOAD_LIMIT=52428800
            - PMA_ARBITRARY=1

    db:
        container_name: example_mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - mysql-data:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "example"
            MYSQL_USER: "devuser"
            MYSQL_PASSWORD: "devpass"
        ports:
            - 3306:3306


volumes:
  mysql-data:
