version: '3.3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: example_wordpress_php74
        depends_on:
            - db
        volumes:
            - ./root:/var/www/html/
        ports:
            - 8000:80

    db:
        container_name: example_wordpress_mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - mysql-data:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "test_db"
            MYSQL_USER: "devuser"
            MYSQL_PASSWORD: "devpass"
        ports:
            - 6033:3306

    dbms:
      image: phpmyadmin
      container_name: example_wordpress_phpmyadmin
      restart: always
      ports:
            - 8080:80
      environment:
            - PMA_ARBITRARY=1

volumes:
  mysql-data:
