version: "3.7"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: ./config/docker-fixes.cnf
        target: /etc/mysql/conf.d/docker-fixes.cnf

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8000:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: devuser
      WORDPRESS_DB_PASSWORD: devpass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        # enable debug messages
        define( 'WP_DEBUG', false );

    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html
      - type: bind
        source: ./config/docker-uploads.ini
        target: /usr/local/etc/php/conf.d/docker-uploads.ini
      - type: bind
        source: ./config/docker-servername.conf
        target: /etc/apache2/conf-enabled/docker-servername.conf

  dbms:
    image: phpmyadmin
    container_name: example_wordpress_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
